sonar.projectKey=ifs24029-pabwe2026-nextjs
sonar.projectName=ifs24029-pabwe2026-nextjs

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,.next/**,dist/**,src/setupTests.ts,src/test-utils.tsx,**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx

# File yang tidak dihitung coverage-nya (disamakan dengan exclude di vitest.config.mts)
sonar.coverage.exclusions=src/app/**,src/components/Providers.tsx,src/hooks/redux.ts,src/lib/config.ts,src/lib/noop.js,src/types/**,src/server.ts,src/setupTests.ts,src/test-utils.tsx,**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx

# Hindari deteksi duplikasi pada file test
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx